name: AWS-BeanStalk-Deploy

env:
  APP_S3_BUCKET_NAME: "myalx" # BENSTALK S3 BUCKET NAME
  APP_NAME : "alx-zone" # BENSTALK APP NAME
  ENV_NAME: "Alxzone-env" # YOUR BENSTALK APP ENV NAME
  DEPLOY_PKG_NAME: "github-action-alx-zone_${{ github.sha }}.zip" # ZIP FILE NAME
  AWS_REGION_NAME: "us-east-1" # REGION TOD DEPLOY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  continuous_integration:
    runs-on: [ubuntu-latest]
    
    steps:
     - name: Clone repo
       uses: actions/checkout@v1
    
     - name: Make zip file
       run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*
       
     - name: Configure Access to AWS
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ env.AWS_REGION_NAME }}
     
     - name: push zip to S3
       run: aws s3 cp ${{ env.DEPLOY_PKG_NAME }} s3://${{ env.APP_S3_BUCKET_NAME }}/
     
     - name: Print msg
       run: echo "CI part is finished"
   
 
  continuous_deplyment:
    runs-on: ubuntu-latest
    needs: [continuous_integration]

    steps:
     - name: Configure Access to AWS
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ env.AWS_REGION_NAME }}
    
     - name: Create new App
       run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.APP_NAME }} \
        --source-bundle S3Bucket="${{ env.APP_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PKG_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "SHA-${{ github.sha }}"
       
     - name: Deploy new App Version
       run : aws elasticbeanstalk update-environment --environment-name ${{ env.ENV_NAME }} --version-label "Ver-${{ github.sha }}"
      
     - name: Print msg
       run : echo "CD part is finished"
