# pipeline

name: ALX-zone CI
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - master
jobs:
  tests:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: First test
        run: echo "First test running"
  deploy:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Deploy code
        run: echo "Deploying code"
        
        
        
        
        
