# pipeline

name: ALX-zone CI
env: 
  APP_NAME: "Flask_App"
  


on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - master
jobs:
  tests:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: First test
        run: echo "First test running"
      
      - name: List current folder
        run : ls

      - name: Git clone
        uses: actions/checkout@v1
          
      - name: List current folder again
        run : ls
        
  deploy:
    runs-on: [ubuntu-latest]
    needs: [tests]
    steps:
      - name: Deploy code
        run: echo "Deploying code"
        
      - name: Execute command
        run: pwd
        
      - name: Success Message
        run: echo "${{ env.APP_NAME }} is Deployed"
        
        
        
        
