# pipeline

name: ALX-zone CI
env: 
  APP_NAME: "Flask_App"
  


on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - master
jobs:
  tests:
    runs-on: ${{ martix.os }}
  
    strategy:
     matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: First test
        run: echo "First test running"
      
      - name: List current folder
        run : ls

      - name: Git clone
        uses: actions/checkout@v1
        
      - name: Check python version
        run: python --version
        
        
  deploy:
    runs-on: ${{ martix.os }}
    
    strategy:
     matrix: 
      os: [ubuntu-latest, windows-latest, macOs-latest]
    needs: [tests]
    steps:
      - name: Deploy code
        run: echo "Deploying code"
        
      - name: Execute command
        run: ls
        
      - name: Success Message
        run: echo "${{ env.APP_NAME }} is Deployed"
      
        
        
        
